wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1704713704
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      - 14
      - 33
      - 41
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 3
      - 5
      - 11
      - 14
      - 33
      - 41
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      4: 3.9.0
      5: 0.12.21
      6: 4.18.0
      8:
      - 3
      - 5
